version: "3.8"
services:
    backend:
        image: harshj/red_hat_backend
        ports:
            - "8000:8000"
            - "8005:8005"
        depends_on:
            - db
    # frontend:
    #     image: harshj/red_hat_frontend
    #     ports:
    #         - "3000:3000"
    db:
        image: harshj/red_hat_database
        restart: always
        ports:
            - "5432:5432"
